name: AdminHax
version: '${project.version}'
main: simplexity.adminhax.AdminHax
description: "A plugin that allows fun but kinda game-breaking commands."
author: Simplexity
api-version: '1.20'

commands:
  hat:
    permission: adminhax.commands.hat
    description: Allows players to put items on their helmet slot
  flyspeed:
    permission: adminhax.commands.speed.fly
    description: Change your flight speed
    aliases: [fs]
  walkspeed:
    permission: adminhax.commands.speed.walk
    description: Change your walk speed
    aliases: [ws]
  fly:
    permission: adminhax.commands.fly
    description: Toggle flight for yourself or others
  feed:
    permission: adminhax.commands.feed
    description: Refill hunger
  heal:
    permission: adminhax.commands.heal
    description: Restore health
  repair:
    permission: adminhax.commands.repair
    description: Repair items
  godmode:
    permission: adminhax.commands.godmode
    description: Toggle invincibility
  broadcastmsg:
    permission: adminhax.commands.broadcast
    description: Broadcast a message to the server
    aliases: [broadcast]
  rename:
    permission: adminhax.commands.rename
    description: Rename an item in hand
  adminhaxreload:
    permission: adminhax.reload
    description: Reload the plugin

permissions:
  adminhax:
    description: Base permissions for AdminHax
    children:
      adminhax.commands.speed.walk: true
      adminhax.commands.speed.fly: true
      adminhax.commands.fly: true
      adminhax.commands.feed: true
      adminhax.commands.heal: true
      adminhax.commands.repair: true
      adminhax.commands.godmode: true
      adminhax.commands.broadcast: true
      adminhax.commands.rename: true

  adminhax.commands.speed:
    description: Permissions for speed commands
    children:
      adminhax.commands.speed.walk: true
      adminhax.commands.speed.fly: true

  adminhax.commands.speed.walk:
    default: op
    description: Change your walk speed
  adminhax.commands.speed.fly:
    default: op
    description: Change your fly speed

  adminhax.commands.fly:
    default: op
    description: Toggle flight
  adminhax.commands.feed:
    default: op
    description: Refill hunger
  adminhax.commands.heal:
    default: op
    description: Restore health

  adminhax.commands.repair:
    description: Repair commands
    children:
      adminhax.commands.repair.hand: true
      adminhax.commands.repair.hotbar: true
      adminhax.commands.repair.inventory: true
      adminhax.commands.repair.armor: true
      adminhax.commands.repair.all: true

  adminhax.commands.repair.hand:
    default: op
    description: Repair the item in your hand
  adminhax.commands.repair.hotbar:
    default: op
    description: Repair items in your hotbar
  adminhax.commands.repair.inventory:
    default: op
    description: Repair items in your inventory
  adminhax.commands.repair.armor:
    default: op
    description: Repair your armor
  adminhax.commands.repair.all:
    default: op
    description: Repair all items

  adminhax.commands.godmode:
    default: op
    description: Toggle invincibility
  adminhax.commands.broadcast:
    default: op
    description: Broadcast a server-wide message
  adminhax.commands.rename:
    description: Rename commands
    children:
      adminhax.commands.rename.color: true
      adminhax.commands.rename.format: true
  adminhax.bypass.rename.length:
    description: Bypass the configured max length of item names (Note, may cause unwanted visual behavior with names going out of screen)
    default: false

  adminhax.commands.rename.color:
    description: Rename with colors
    children:
      adminhax.commands.rename.color.gradient: true
      adminhax.commands.rename.color.rainbow: true
  adminhax.commands.rename.color.gradient:
    default: op
    description: Use gradient colors in renames
  adminhax.commands.rename.color.rainbow:
    default: op
    description: Use rainbow tag in renames

  adminhax.commands.rename.format:
    description: Rename with formats
    children:
      adminhax.commands.rename.format.strikethrough: true
      adminhax.commands.rename.format.italic: true
      adminhax.commands.rename.format.bold: true
      adminhax.commands.rename.format.obfuscated: true
  adminhax.commands.rename.format.strikethrough:
    default: op
    description: Use strikethrough format
  adminhax.commands.rename.format.italic:
    default: op
    description: Use italic format
  adminhax.commands.rename.format.bold:
    default: op
    description: Use bold format
  adminhax.commands.rename.format.obfuscated:
    default: op
    description: Use obfuscated format
  adminhax.commands.hat:
    default: op
    description: Allows a user to put items in their helmet slot with the /hat command
  adminhax.reload:
    default: op
    description: Reload the plugin
